name: CI

on:
  push:
    branches: [ develop, TECH-Github-Actions ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            "$HOME/.gradle/caches/"
            "$HOME/.gradle/wrapper/"
            "$HOME/.android/build-cache"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Run
        run: |
          rvm install 2.6.3
          rvm use 2.6.3
          bundle install
          FASTLANE_SKIP_UPDATE_CHECK=1 bundle exec fastlane shipit
